apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vn
  template:
    metadata:
      labels:
        app: nginx-vn
    spec:
      containers:
      - name: nginx-vn
        image: nginx
        resources:
          requests:
            cpu: '1'
            memory: '2Gi'
          limits:
            cpu: '1'
            memory: '2Gi'
      tolerations:
      - key: virtual-kubelet.io/provider
        value: azure
        operator: Equal
        effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - virtual-kubelet
