FROM debian

RUN apt-get update
RUN apt-get install host -y
RUN apt-get install iftop -y
RUN apt-get install curl -y
RUN apt-get install wget -y
RUN apt-get install ssh -y

# Comment

CMD [ "sleep", "infinity" ]