apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloparis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloparis-app
  template:
    metadata:
      labels:
        app: helloparis-app
    spec:
      containers:
      - name: helloparis
        image: mikhegn-microsoft.azurecr.io/helloparis:v1001
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: helloparis-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloparis-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50